services:
  - type: web
    name: airesume-backend
    runtime: docker
    rootDir: Backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_NAME
        value: resume_ai
      - key: DB_PORT
        value: 3306
      - key: APP_AUTH_DEBUG_RESET_CODE
        value: "false"
